\timing on
\echo truncating table sparcs.inpatient...
TRUNCATE TABLE sparcs.inpatient;

\echo upload inpatient data
\echo 1998
\copy sparcs.inpatient from '../../line-transform/app/output/120903IUM98_E.DAT.csv' WITH (FORMAT CSV, NULL '')

\echo 1999
\copy sparcs.inpatient from '../../line-transform/app/output/120903IUM99_E.DAT.csv' WITH (FORMAT CSV, NULL '')

\echo 2000
\copy sparcs.inpatient from '../../line-transform/app/output/120903IUM00_E.DAT.csv' WITH (FORMAT CSV, NULL '')

\echo 2001
\copy sparcs.inpatient from '../../line-transform/app/output/120903IUM01_E.DAT.csv' WITH (FORMAT CSV, NULL '')

\echo 2002
\copy sparcs.inpatient from '../../line-transform/app/output/120903IUM02_E.DAT.csv' WITH (FORMAT CSV, NULL '')

\echo 2003
\copy sparcs.inpatient from '../../line-transform/app/output/120903IUM03_E.DAT.csv' WITH (FORMAT CSV, NULL '')

\echo 2004
\copy sparcs.inpatient from '../../line-transform/app/output/120903IUM04_E.DAT.csv' WITH (FORMAT CSV, NULL '')

\echo 2005
\copy sparcs.inpatient from '../../line-transform/app/output/120903IUM05_E.DAT.csv' WITH (FORMAT CSV, NULL '')

\echo 2006
\copy sparcs.inpatient from '../../line-transform/app/output/120903IUM06_E.DAT.csv' WITH (FORMAT CSV, NULL '')

\echo 2007
\copy sparcs.inpatient from '../../line-transform/app/output/120903IUM07_E.DAT.csv' WITH (FORMAT CSV, NULL '')

\echo 2008
\copy sparcs.inpatient from '../../line-transform/app/output/120903IUM08_E.DAT.csv' WITH (FORMAT CSV, NULL '')

\echo 2009
\copy sparcs.inpatient from '../../line-transform/app/output/120903IUM09_E.DAT.csv' WITH (FORMAT CSV, NULL '')

\echo 2010
\copy sparcs.inpatient from '../../line-transform/app/output/120903IUM10_E.DAT.csv' WITH (FORMAT CSV, NULL '')

\echo 2011
\copy sparcs.inpatient from '../../line-transform/app/output/120903IUM11_E.DAT.csv' WITH (FORMAT CSV, NULL '')

\echo 2012
\copy sparcs.inpatient from '../../line-transform/app/output/120903IUM12_E.DAT.csv' WITH (FORMAT CSV, NULL '')

\echo 2013
\copy sparcs.inpatient from '../../line-transform/app/output/120903IUM13_E.DAT.csv' WITH (FORMAT CSV, NULL '')

\echo 2014
\copy sparcs.inpatient from '../../line-transform/app/output/120903IUM14_E.DAT.csv' WITH (FORMAT CSV, NULL '')
